---
year: '2024'
booktitle: Proceedings of The Workshop on Classifier Learning from Difficult Data
volume: '263'
shortname: CLD2
start: &1 2024-10-19
end: 2024-10-20
published: 2024-10-21
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: CLD2-2024
month: 0
cycles: false
bibtex_editor: Zyblewski, Pawel and Grana, Manuel and Pawel, Ksieniewicz and Minku,
  Leandro
editor:
- given: Pawel
  family: Zyblewski
- given: Manuel
  family: Grana
- given: Ksieniewicz
  family: Pawel
- given: Leandro
  family: Minku
title: Proceedings of Machine Learning Research
description: |
  Proceedings of The Workshop on Classifier Learning from Difficult Data
    Held in Santiago de Compostella, Spain on 19-20 October 2024

  Published as Volume 263 by the Proceedings of Machine Learning Research on 21 October 2024.

  Volume Edited by:
    Pawel Zyblewski
    Manuel Grana
    Ksieniewicz Pawel
    Leandro Minku

  Series Editors:
    Neil D. Lawrence
date_str: 19--20 Oct
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v263"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v263
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v263
email: ''
conference:
  name: Classifier Learning from Difficult Data
  url: https://cldd.kssk.pwr.edu.pl
  location: Santiago de Compostella, Spain
  dates:
  - *1
  - 2024-10-20
analytics:
  google:
    tracking_id: UA-92432422-1
orig_bibfile: "/Users/neil/mlresearch/v263/cldd24.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v263/cldd24.bib
